"""Enable Row-Level Security on all tenant-scoped tables.

Applies RLS policies generated by src.core.rls.generate_rls_sql().
Each tenant table gets a policy that restricts rows to the current
user via current_setting('app.current_user_id').

Revision ID: 20260212_rls
Revises: 20260212_html
Create Date: 2026-02-12
"""
from alembic import op

from src.core.rls import generate_rls_sql

# revision identifiers, used by Alembic.
revision = '20260212_rls'
down_revision = '20260212_html'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for stmt in generate_rls_sql():
        op.execute(stmt)


def downgrade() -> None:
    tables = [
        "projects", "documents", "variables", "prompts",
        "processing_jobs", "extractions", "extraction_feedback",
        "processing_logs", "document_chunks",
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
